package com.mycompany.proyectoparqueos;

import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class MenuConfigurarParqueo extends javax.swing.JFrame {
     Administrador admin;
     Parqueo parqueo;
    /**
     * Creates new form MenuConfigurarParqueo
     * @param admin
     * @param parqueo
     */
    public MenuConfigurarParqueo(Administrador admin, Parqueo parqueo) {
        initComponents();
        setAdmin(admin);
        setParqueo(parqueo);
    }

    /**
     *
     * @param administrador
     */
    public void setAdmin(Administrador administrador){
        admin = administrador;
    }
        
    /**
     *
     * @param parqueo
     */
    public void setParqueo(Parqueo parqueo){
            this.parqueo = parqueo;
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        btnConfigurarParqueo1 = new javax.swing.JButton();
        inpIdentificacion = new javax.swing.JTextField();
        inpTiempoMinimo1 = new javax.swing.JTextField();
        inpAgregarDesde2 = new javax.swing.JTextField();
        lblNombre10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblNombre1 = new javax.swing.JLabel();
        lblNombre2 = new javax.swing.JLabel();
        lblNombre3 = new javax.swing.JLabel();
        lblNombre4 = new javax.swing.JLabel();
        inpHorarioCierra = new javax.swing.JTextField();
        inpPrecioPorHora = new javax.swing.JTextField();
        lblNombre6 = new javax.swing.JLabel();
        lblNombre8 = new javax.swing.JLabel();
        inpHorarioAbre = new javax.swing.JTextField();
        inpTiempoMinimo = new javax.swing.JTextField();
        inpCostoMulta = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        lblNombre5 = new javax.swing.JLabel();
        inpAgregarDesde = new javax.swing.JTextField();
        inpAgregarHasta = new javax.swing.JTextField();
        lblNombre7 = new javax.swing.JLabel();
        inpEliminarHasta = new javax.swing.JTextField();
        inpEliminarDesde = new javax.swing.JTextField();
        lblNombre9 = new javax.swing.JLabel();
        lblNombre11 = new javax.swing.JLabel();

        jLabel8.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Identificacion de usuario: ");

        btnConfigurarParqueo1.setBackground(new java.awt.Color(204, 204, 204));
        btnConfigurarParqueo1.setText("CONFIGURAR PARQUEO");
        btnConfigurarParqueo1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConfigurarParqueo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfigurarParqueo1ActionPerformed(evt);
            }
        });

        inpIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpIdentificacionActionPerformed(evt);
            }
        });

        inpTiempoMinimo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpTiempoMinimo1ActionPerformed(evt);
            }
        });

        inpAgregarDesde2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpAgregarDesde2ActionPerformed(evt);
            }
        });

        lblNombre10.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        lblNombre10.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre10.setText("Abre:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel2.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CONFIGURAR PARQUEO");

        btnVolver.setBackground(new java.awt.Color(204, 204, 204));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));

        lblNombre.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Precio por hora:");

        lblNombre1.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        lblNombre1.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre1.setText("Tiempo mínimo:");

        lblNombre2.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        lblNombre2.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre2.setText("Costo de la multa:");

        lblNombre3.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        lblNombre3.setForeground(new java.awt.Color(255, 255, 255));

        lblNombre4.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        lblNombre4.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre4.setText("Horario de regulación:");

        inpHorarioCierra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpHorarioCierraActionPerformed(evt);
            }
        });

        inpPrecioPorHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpPrecioPorHoraActionPerformed(evt);
            }
        });

        lblNombre6.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        lblNombre6.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre6.setText("Cierra:");

        lblNombre8.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        lblNombre8.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre8.setText("Desde:");

        inpHorarioAbre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpHorarioAbreActionPerformed(evt);
            }
        });

        inpTiempoMinimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpTiempoMinimoActionPerformed(evt);
            }
        });

        inpCostoMulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpCostoMultaActionPerformed(evt);
            }
        });

        btnAceptar.setBackground(new java.awt.Color(204, 204, 204));
        btnAceptar.setText("Aceptar");
        btnAceptar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        lblNombre5.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        lblNombre5.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre5.setText("Agregar Espacios:");

        inpAgregarDesde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpAgregarDesdeActionPerformed(evt);
            }
        });

        inpAgregarHasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpAgregarHastaActionPerformed(evt);
            }
        });

        lblNombre7.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        lblNombre7.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre7.setText("Eliminar Espacios:");

        inpEliminarHasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpEliminarHastaActionPerformed(evt);
            }
        });

        inpEliminarDesde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpEliminarDesdeActionPerformed(evt);
            }
        });

        lblNombre9.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        lblNombre9.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre9.setText("Hasta:");

        lblNombre11.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        lblNombre11.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre11.setText("Abre:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVolver)
                        .addGap(140, 140, 140)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(245, 245, 245)
                                .addComponent(lblNombre11, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(lblNombre6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblNombre7, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(inpEliminarDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(inpEliminarHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(inpHorarioCierra, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(inpAgregarHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(lblNombre4, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(inpHorarioAbre, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(lblNombre3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(115, 115, 115)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(lblNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(inpPrecioPorHora, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(inpTiempoMinimo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(inpCostoMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(lblNombre5, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(inpAgregarDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(lblNombre8, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(lblNombre9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVolver)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombre11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inpHorarioAbre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inpHorarioCierra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombre4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inpPrecioPorHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inpTiempoMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inpCostoMulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombre9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inpAgregarDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inpAgregarHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(154, 154, 154)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inpEliminarDesde, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNombre7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(inpEliminarHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        MenuAdministrador pantalla = new MenuAdministrador(admin, parqueo);
        pantalla.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnVolverActionPerformed
// <editor-fold defaultstate="collapsed" desc="Inputs">   
    private void btnConfigurarParqueo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfigurarParqueo1ActionPerformed

    }//GEN-LAST:event_btnConfigurarParqueo1ActionPerformed

    private void inpIdentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpIdentificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpIdentificacionActionPerformed

    private void inpHorarioCierraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpHorarioCierraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpHorarioCierraActionPerformed

    private void inpPrecioPorHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpPrecioPorHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpPrecioPorHoraActionPerformed

    private void inpHorarioAbreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpHorarioAbreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpHorarioAbreActionPerformed

    private void inpTiempoMinimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpTiempoMinimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpTiempoMinimoActionPerformed

    private void inpTiempoMinimo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpTiempoMinimo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpTiempoMinimo1ActionPerformed

    private void inpCostoMultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpCostoMultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpCostoMultaActionPerformed
// </editor-fold >  
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
                                    
        String abreText = inpHorarioAbre.getText();
        String cierraText = inpHorarioCierra.getText();
        parqueo.setAbre(abreText);
        parqueo.setCierra(cierraText);

        try {
            int precioHora = Integer.parseInt(inpPrecioPorHora.getText());
            parqueo.setPrecioHora(precioHora);
        } 
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Por favor, ingresa un número válido para el precio por hora.", "Error", JOptionPane.ERROR_MESSAGE);
        }

        try {
            int tiempoMinimo = Integer.parseInt(inpTiempoMinimo.getText());
            parqueo.setTiempoMinimo(tiempoMinimo);
        } 
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Por favor, ingresa un número válido para el tiempo mínimo.", "Error", JOptionPane.ERROR_MESSAGE);
        }

        try {
            int costoMulta = Integer.parseInt(inpCostoMulta.getText());
            parqueo.setCostoMulta(costoMulta);
        } 
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Por favor, ingresa un número válido para el costo de la multa.", "Error", JOptionPane.ERROR_MESSAGE);
        }

        // Agregar Espacios
        try {
            if (!inpAgregarDesde.getText().isEmpty() && !inpAgregarHasta.getText().isEmpty()) {
                int agregarDesde = Integer.parseInt(inpAgregarDesde.getText());
                int agregarHasta = Integer.parseInt(inpAgregarHasta.getText());

                if (agregarDesde < agregarHasta) {
                    parqueo.agregarGrupoEspacios(agregarDesde, agregarHasta);
                } else {
                    JOptionPane.showMessageDialog(null, "El valor 'Desde' debe ser menor que 'Hasta'.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                System.out.println("No se agregó ningún espacio porque los campos están vacíos.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Por favor ingresa números válidos para los espacios.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocurrió un error inesperado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

        // Eliminar Espacios
        try {
            if (!inpEliminarDesde.getText().isEmpty() && !inpEliminarHasta.getText().isEmpty()) {
                int eliminarDesde = Integer.parseInt(inpEliminarDesde.getText());
                int eliminarHasta = Integer.parseInt(inpEliminarHasta.getText());

                if (eliminarDesde < eliminarHasta) {
                    parqueo.eliminarGrupoEspacios(eliminarDesde, eliminarHasta);
                } else {
                    JOptionPane.showMessageDialog(null, "El valor 'Desde' debe ser menor que 'Hasta'.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                System.out.println("No se eliminó ningún espacio porque los campos están vacíos.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Por favor ingresa números válidos para los espacios.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocurrió un error inesperado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

        // Guardar información en archivo de Parqueo
        File archivoParqueo = new File("Parqueo.txt");
        parqueo.guardarParqueo(archivoParqueo);

        // Enviar correo con los detalles de la nueva configuración del parqueo
        Correo correo = new Correo("juanpacamal08@gmail.com", "adqs eueu mrbs vngz", "smtp.gmail.com");
        String destinatario = admin.getCorreo();
        String asunto = "Nueva Configuración del Parqueo";
        String cuerpo = String.format(
            "Nueva configuración del parqueo:\n" +
            "Horario de apertura: %s\n" +
            "Horario de cierre: %s\n" +
            "Precio por hora: %d\n" +
            "Tiempo mínimo: %d minutos\n" +
            "Costo de la multa: %d colones\n",
            abreText, cierraText, parqueo.getPrecioHora(), parqueo.getTiempoMinimo(), parqueo.getCostoMulta()
        );
        correo.enviarCorreo(destinatario, asunto, cuerpo);

        JOptionPane.showMessageDialog(null, "Configuración guardada y correo enviado.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

        // Regresar al menú administrador
        MenuAdministrador pantalla = new MenuAdministrador(admin, parqueo);
        pantalla.setVisible(true);
        this.setVisible(false);


        
    }//GEN-LAST:event_btnAceptarActionPerformed
// <editor-fold defaultstate="collapsed" desc="Inputs"> 
    private void inpAgregarDesdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpAgregarDesdeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpAgregarDesdeActionPerformed

    private void inpAgregarHastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpAgregarHastaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpAgregarHastaActionPerformed

    private void inpEliminarHastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpEliminarHastaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpEliminarHastaActionPerformed

    private void inpAgregarDesde2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpAgregarDesde2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpAgregarDesde2ActionPerformed

    private void inpEliminarDesdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpEliminarDesdeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpEliminarDesdeActionPerformed
// </editor-fold > 
    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuConfigurarParqueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuConfigurarParqueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuConfigurarParqueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuConfigurarParqueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuConfigurarParqueo(admin, parqueo).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnConfigurarParqueo1;
    private javax.swing.JButton btnVolver;
    private javax.swing.JTextField inpAgregarDesde;
    private javax.swing.JTextField inpAgregarDesde2;
    private javax.swing.JTextField inpAgregarHasta;
    private javax.swing.JTextField inpCostoMulta;
    private javax.swing.JTextField inpEliminarDesde;
    private javax.swing.JTextField inpEliminarHasta;
    private javax.swing.JTextField inpHorarioAbre;
    private javax.swing.JTextField inpHorarioCierra;
    private javax.swing.JTextField inpIdentificacion;
    private javax.swing.JTextField inpPrecioPorHora;
    private javax.swing.JTextField inpTiempoMinimo;
    private javax.swing.JTextField inpTiempoMinimo1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblNombre10;
    private javax.swing.JLabel lblNombre11;
    private javax.swing.JLabel lblNombre2;
    private javax.swing.JLabel lblNombre3;
    private javax.swing.JLabel lblNombre4;
    private javax.swing.JLabel lblNombre5;
    private javax.swing.JLabel lblNombre6;
    private javax.swing.JLabel lblNombre7;
    private javax.swing.JLabel lblNombre8;
    private javax.swing.JLabel lblNombre9;
    // End of variables declaration//GEN-END:variables
}
